name: nonsmoking
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.5
  flutter_launcher_icons: ^0.13.1
  lottie: ^2.7.0
  shared_preferences: ^2.2.0
  intl: ^0.18.1

  #19.2.1 버전은 유투브의 http를 사용하기 위함
  #flutter_local_notifications: ^19.2.1
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2
  #timezone: ^0.10.1

  #알람기능 사용시, workmanger로 사용
  workmanager: ^0.6.0

  google_mobile_ads: ^4.0.0

  #firebase 사용
  firebase_core: ^3.0.0
  firebase_crashlytics: ^4.0.0
  firebase_analytics: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.3.5

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/
    - assets/lung_recover.json
    - assets/app_icon.png
    - assets/icons/app_icon.png
    - assets/tree_stage_1.png
    - assets/tree_stage_2.png
    - assets/tree_stage_3.png
    - assets/tree_stage_4.png
    - assets/tree_stage_5.png
    - assets/water_drop.json
    - assets/lottie/Cig.json
    - assets/lottie/water.json
    #- assets/lottie/water_drop.json


  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true

flutter_native_splash:
  color: "#ffffff"  # 배경색
  image: assets/app_icon.png
  branding: assets/branding.png # 필요 시

  android: true
  ios: true
  web: false

  android_gravity: center
  ios_content_mode: center